hw2: layout & intent
VovaMiller/android-course-2018 pull request #3
Opened 2018-11-30 10:53 UTC by VovaMiller

Второе ДЗ: “верстка и intent”

2018-11-30 20:45 UTC, IvanShafran requested changes
Пока ставлю 6
Остальные баллы тут:
1) Использовать onSaveInstanceState вместо статической переменной -- +2 балла
2) Не использовать ConstraintLayout там где не нужно. Например, просто убери их и позиционируй только кнопки. + 1 балл
3) Приведение к Java Code Style, использование модификаторов private, нормальные названия переменных и классов + 1 балл

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="fullSensor">
А зачем?

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/MainActivity.java
> +    Button button_1;
1) Если поля нужны только внутри класса, то нужен модификатор private
2) button_1 -- плохое название. Должно быть осмысленное
3) Java code style -- это camelCase для полей. Например: emailButton

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/MainActivity.java
> +                Intent emailIntent = new Intent(Intent.ACTION_SENDTO, Uri.fromParts(
Хорошо бы это вынести в отдельный метод

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/MainActivity.java
> +    public static String getApplicationName(Context context) {
Странно, что это находится внутри Activity

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/MainActivity.java
> +    public static String getApplicationName(Context context) {
Почему не в утилитном классе?

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/res/layout/activity_main.xml
> +    <android.support.constraint.ConstraintLayout
Основной смысл constraint layout уменьшить вложенность, поэтому использование нескольких constraint layout внутри одной разметки -- плохо

2018-11-30 20:45 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/SecondActivity.java
> +    static String editTextMemory = null;
Чтобы сохранить значение при повороте Activity нужно использовать onSaveInstanceState и onRestoreInstanceState, а не статическую переменную.

2018-12-03 10:07 UTC, VovaMiller commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="fullSensor">
Хотел, чтобы в эмуляторе при повороте экрана ориентация сменялась автоматически.
Без этого после поворота приходилось в панели навигации нажимать на кнопку.

2018-12-03 10:09 UTC, VovaMiller commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/SecondActivity.java
> +    static String editTextMemory = null;
Правильно ли я понял, что для сохранения значения при повороте ничего дополнительно делать не нужно, если в EditText задан android:id?

2018-12-04 20:34 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/SecondActivity.java
> +    static String editTextMemory = null;
Ага. Задание было изучить этот вопрос. Если бы этого кода не было или было через onSaveInstanceState, то я бы не придирался. Ну а со static переменной совсем плохо

2018-12-04 20:45 UTC, IvanShafran approved these changes

2018-12-04 20:45 UTC, IvanShafran commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="fullSensor">
В настройках android есть "блокировать поворот". Наверное, это в эмуляторе включено. Потяни за notification bar и выключи эту опцию.
Так получается, что ты её игнорируешь. А это не совсем хорошо для пользователя

2018-12-04 20:45 UTC, IvanShafran commented on app/src/main/java/com/polygon/myxtap/myxtapapplication/AppUtilities.java
> +public class AppUtilities {
Канонично ещё делать приватный конструктор, чтобы никто утилитный класс не смог создать

2018-12-04 20:45 UTC, merged